# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: asimov_diagnostics.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'asimov_diagnostics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61simov_diagnostics.proto\x12\tasimov.io\"\xa6\x01\n\x05\x41lert\x12\x0e\n\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n\x08severity\x18\x02 \x01(\rR\x08severity\x12\x14\n\x05value\x18\x03 \x01(\rR\x05value\x12\x1c\n\tthreshold\x18\x04 \x01(\rR\tthreshold\x12 \n\x0c\x66irst_set_us\x18\x05 \x01(\x04R\nfirstSetUs\x12\x1b\n\tsource_id\x18\x06 \x01(\rR\x08sourceId\"p\n\rThreadMetrics\x12 \n\x0cmax_cycle_us\x18\x01 \x01(\x04R\nmaxCycleUs\x12 \n\x0c\x61vg_cycle_us\x18\x02 \x01(\x04R\navgCycleUs\x12\x1b\n\tjitter_us\x18\x03 \x01(\x03R\x08jitterUs\"\x8a\x01\n\x0bOnnxMetrics\x12(\n\x10\x61vg_inference_ms\x18\x01 \x01(\x02R\x0e\x61vgInferenceMs\x12(\n\x10max_inference_ms\x18\x02 \x01(\x02R\x0emaxInferenceMs\x12\'\n\x0finference_count\x18\x03 \x01(\x04R\x0einferenceCount\"\x89\x01\n\nCanMetrics\x12\x1f\n\x0b\x66rames_sent\x18\x01 \x01(\x04R\nframesSent\x12\'\n\x0f\x66rames_received\x18\x02 \x01(\x04R\x0e\x66ramesReceived\x12\x16\n\x06\x65rrors\x18\x03 \x01(\x04R\x06\x65rrors\x12\x19\n\x08\x62us_offs\x18\x04 \x01(\x04R\x07\x62usOffsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asimov_diagnostics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALERT']._serialized_start=40
  _globals['_ALERT']._serialized_end=206
  _globals['_THREADMETRICS']._serialized_start=208
  _globals['_THREADMETRICS']._serialized_end=320
  _globals['_ONNXMETRICS']._serialized_start=323
  _globals['_ONNXMETRICS']._serialized_end=461
  _globals['_CANMETRICS']._serialized_start=464
  _globals['_CANMETRICS']._serialized_end=601
# @@protoc_insertion_point(module_scope)
