# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: asimov_command.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'asimov_command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import asimov_common_pb2 as asimov__common__pb2
from . import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61simov_command.proto\x12\tasimov.io\x1a\x13\x61simov_common.proto\x1a\x0cnanopb.proto\"E\n\x0fVelocityCommand\x12\x0e\n\x02vx\x18\x01 \x01(\x02R\x02vx\x12\x0e\n\x02vy\x18\x02 \x01(\x02R\x02vy\x12\x12\n\x04vyaw\x18\x03 \x01(\x02R\x04vyaw\"b\n\rAllTrajectory\x12#\n\tpositions\x18\x01 \x03(\x02\x42\x05\x92?\x02\x10\x19R\tpositions\x12\x15\n\x02kp\x18\x02 \x03(\x02\x42\x05\x92?\x02\x10\x19R\x02kp\x12\x15\n\x02kd\x18\x03 \x03(\x02\x42\x05\x92?\x02\x10\x19R\x02kd\"\xaf\x01\n\nEolCommand\x12,\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x14.asimov.io.EolActionR\x06\x61\x63tion\x12\x19\n\x08motor_id\x18\x02 \x01(\rR\x07motorId\x12\x1a\n\x08position\x18\x03 \x01(\x02R\x08position\x12\x0e\n\x02kp\x18\x04 \x01(\x02R\x02kp\x12\x0e\n\x02kd\x18\x05 \x01(\x02R\x02kd\x12\x1c\n\nnew_can_id\x18\x06 \x01(\rR\x08newCanId\"\xa2\x03\n\x0cRobotCommand\x12*\n\x04mode\x18\x01 \x01(\x0e\x32\x16.asimov.io.ControlModeR\x04mode\x12\x42\n\x0f\x63ommand_control\x18\x02 \x01(\x0e\x32\x19.asimov.io.CommandControlR\x0e\x63ommandControl\x12\x34\n\x06policy\x18\x03 \x01(\x0b\x32\x1a.asimov.io.VelocityCommandH\x00R\x06policy\x12\x41\n\x0e\x61ll_trajectory\x18\x05 \x01(\x0b\x32\x18.asimov.io.AllTrajectoryH\x00R\rallTrajectory\x12)\n\x03\x65ol\x18\t \x01(\x0b\x32\x15.asimov.io.EolCommandH\x00R\x03\x65ol\x12!\n\x0ctimestamp_us\x18\x06 \x01(\x04R\x0btimestampUs\x12\x1a\n\x08sequence\x18\x07 \x01(\rR\x08sequence\x12)\n\x10protocol_version\x18\x08 \x01(\rR\x0fprotocolVersionB\x0e\n\x0c\x63ommand_dataJ\x04\x08\x04\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asimov_command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALLTRAJECTORY'].fields_by_name['positions']._loaded_options = None
  _globals['_ALLTRAJECTORY'].fields_by_name['positions']._serialized_options = b'\222?\002\020\031'
  _globals['_ALLTRAJECTORY'].fields_by_name['kp']._loaded_options = None
  _globals['_ALLTRAJECTORY'].fields_by_name['kp']._serialized_options = b'\222?\002\020\031'
  _globals['_ALLTRAJECTORY'].fields_by_name['kd']._loaded_options = None
  _globals['_ALLTRAJECTORY'].fields_by_name['kd']._serialized_options = b'\222?\002\020\031'
  _globals['_VELOCITYCOMMAND']._serialized_start=70
  _globals['_VELOCITYCOMMAND']._serialized_end=139
  _globals['_ALLTRAJECTORY']._serialized_start=141
  _globals['_ALLTRAJECTORY']._serialized_end=239
  _globals['_EOLCOMMAND']._serialized_start=242
  _globals['_EOLCOMMAND']._serialized_end=417
  _globals['_ROBOTCOMMAND']._serialized_start=420
  _globals['_ROBOTCOMMAND']._serialized_end=838
# @@protoc_insertion_point(module_scope)
