# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: asimov_common.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'asimov_common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61simov_common.proto\x12\tasimov.io*Y\n\x0b\x43ontrolMode\x12\x15\n\x11\x43ONTROL_MODE_DAMP\x10\x00\x12\x16\n\x12\x43ONTROL_MODE_STAND\x10\x01\x12\x15\n\x11\x43ONTROL_MODE_MOVE\x10\x02\"\x04\x08\x03\x10\x03*R\n\x0e\x43ommandControl\x12\x1a\n\x16\x43OMMAND_CONTROL_POLICY\x10\x00\x12\x1e\n\x1a\x43OMMAND_CONTROL_TRAJECTORY\x10\x01\"\x04\x08\x02\x10\x02*[\n\tEolAction\x12\x12\n\x0e\x45OL_MOVE_MOTOR\x10\x00\x12\x14\n\x10\x45OL_ZERO_ENCODER\x10\x01\x12\x12\n\x0e\x45OL_SET_CAN_ID\x10\x02\x12\x10\n\x0c\x45OL_FINALIZE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asimov_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTROLMODE']._serialized_start=34
  _globals['_CONTROLMODE']._serialized_end=123
  _globals['_COMMANDCONTROL']._serialized_start=125
  _globals['_COMMANDCONTROL']._serialized_end=207
  _globals['_EOLACTION']._serialized_start=209
  _globals['_EOLACTION']._serialized_end=300
# @@protoc_insertion_point(module_scope)
